qwen:
  model: "qwen2.5-7b-instruct"
  custom_llm_provider: "lm_studio"
  api_base: "http://127.0.0.1:1234/v1"

llama3:
  model: "meta-llama-3.1-8b-instruct"
  custom_llm_provider: "lm_studio"
  api_base: "http://127.0.0.1:1234/v1"

groqllama:
  model: "llama-3.3-70b-versatile"
  custom_llm_provider: "groq"
  api_base: null

groqdeepseek:
  model: "deepseek-r1-distill-llama-70b"
  custom_llm_provider: "groq"
  api_base: null